elastic_utils:
  hash: "{{ .Values.credentials.elasticUtilsPasswordHash }}"
curator:
  hash: "{{ .Values.credentials.curatorPasswordHash }}"
admin:
  hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
  #password is: admin
logstash:
  hash: $2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2
  #password is: logstash
kibanaserver:
  hash: "{{ .Values.credentials.kibanaServerPasswordHash }}"
  #password is: kibanaserver
readall:
  hash: $2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2
  #password is: readall
indexlister:
  hash: "{{ .Values.credentials.indexListerPasswordHash }}"
  #password is: indexlister